### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by Zvirtuey** [android/ndk#1292]
I have a compiled “.so” project. The compiled so can run on Android 6.0 machines, but not work on 5. X or 4. X versions.  I try to use makefile and cmake with the same error on the lower version machine, I tried many NDK versions and didn't solve my problem. Can I do anything else?

NDK version ：ndk-r10  and 21.0.6113669
 ABI："armeabi", "armeabi-v7a"

############

    compileSdkVersion 23
    buildToolsVersion "28.0.3"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi", "armeabi-v7a"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jni.srcDirs = []
            jniLibs.srcDir 'libs'
        }
    }

#############
error log:

dlopen("/data/app/com.rzt.sip-1/lib/arm/librzt_sip.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "rztHangup" referenced by "libmgr.so"...
 E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.rzt.sxx, PID: 23671
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rztHangup" referenced by "libmgr.so"...
     at java.lang.Runtime.loadLibrary(Runtime.java:371)
     at java.lang.System.loadLibrary(System.java:988)
     at com.rzt.xlibrary.media.RztMediaJni.<clinit>(RztMediaJni.java:22)
     at com.rzt.xlibrary.media.RztMediaMgr.setAudioRecord(RztMediaMgr.java:578)
     at com.rzt.xlibrary.sip.RztSipMgr.setAudioRecord(RztSipMgr.java:341)
     at com.rzt.sxx.MainActivity.onCreate(MainActivity.java:15)
     at android.app.Activity.performCreate(Activity.java:6127)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
     at android.app.ActivityThread.access$900(ActivityThread.java:187)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
     at android.os.Handler.dispatchMessage(Handler.java:111)
     at android.os.Looper.loop(Looper.java:194)
     at android.app.ActivityThread.main(ActivityThread.java:5877)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by alexcohn** [comment]
Since API 21 (a.k.a. Android 5), the system can resolve library dependencies automatically. On earlier platforms, you need to call `System.Load()` or `dlopen()` for all libraries in right order. If **rztHangup** is defined `libabc.so`, you must load `libabc.so` explicitly before you load `librzt_sip.so` which references this symbol.

**Comment by DanAlbert** [comment]
https://github.com/KeepSafe/ReLinker is great for working around these sorts of issues. If that doesn't solve the problem lmk and I'll I'll reopen, but that sounds likely.

**Comment by Zvirtuey** [comment]
I tried to change the loading order and use https://github.com/KeepSafe/ReLinker  without any change. The problem remains.

######################

06-26 13:59:55.684 16072-16072/? E/art: dlopen("/data/app/com.rzt.sip-1/lib/arm/libmgr.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "rztHangup" referenced by "libmgr.so"...
06-26 13:59:55.685 16072-16072/? W/linker: libmgr.so: unused DT entry: type 0x6ffffffe arg 0x8384
06-26 13:59:55.685 16072-16072/? W/linker: libmgr.so: unused DT entry: type 0x6fffffff arg 0x2
06-26 13:59:55.686 16072-16072/? E/art: dlopen("/data/data/com.rzt.sip/app_lib/libmgr.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "rztHangup" referenced by "libmgr.so"...
06-26 13:59:55.687 16072-16072/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.rzt.sip, PID: 16072
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rztHangup" referenced by "libmgr.so"...
   at java.lang.Runtime.load(Runtime.java:331)
   at java.lang.System.load(System.java:981)
   at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
   at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
   at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
   at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
   at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
   at com.rzt.siplibrary.media.RztMediaJni.<clinit>(RztMediaJni.java:27)
   at com.rzt.siplibrary.media.RztMediaMgr.setAudioRecord(RztMediaMgr.java:578)
   at com.rzt.siplibrary.sip.RztSipMgr.setAudioRecord(RztSipMgr.java:341)
   at com.rzt.sip.MainActivity.onCreate(MainActivity.java:15)
   at android.app.Activity.performCreate(Activity.java:6127)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
   at android.app.ActivityThread.access$900(ActivityThread.java:187)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
   at android.os.Handler.dispatchMessage(Handler.java:111)
   at android.os.Looper.loop(Looper.java:194)
   at android.app.ActivityThread.main(ActivityThread.java:5877)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by rprichard** [comment]
> Since API 21 (a.k.a. Android 5), the system can resolve library dependencies automatically. On earlier platforms, you need to call System.Load() or dlopen() for all libraries in right order. If rztHangup is defined libabc.so, you must load libabc.so explicitly before you load librzt_sip.so which references this symbol.

I think that bug was [fixed in JB-MR2 rather than L](https://android.googlesource.com/platform/bionic/+/refs/heads/master/android-changes-for-ndk-developers.md#changes-to-library-dependency-resolution). If the app hit this bug, then the dlopen call would fail because libapp2.so would be missing.

In this case, we're seeing the effect of the linker redesign in Android 6. It looks like librzt_sip.so depends on libmgr.so, but libmgr.so is calling a symbol (rztHangup), which I'm guessing is exported from librzt_sip.so (or some other dependency of librzt_sip.so). In Android 6, when a library is loaded, the linker searches the entire transitive closure of DT_NEEDED libraries for every symbol reference in the tree. A child library can find a symbol in the parent. (A parent can interpose/override a definition in the child.) IIRC, previous linkers only searched the direct dependencies of the library containing the symbol reference.

ReLinker would try to load libmgr.so before any app library that needs libmgr.so (e.g. librzt_sip.so), so I suspect that would fail even on Android 6.

I suppose the fix is to make sure rztHangup is provided by a library that libmgr.so has a DT_NEEDED dependency on. I think the old Bionic linker rejects circular library dependencies ("recursive link to" error), so maybe some refactoring would be needed.

**Comment by Zvirtuey** [comment]
I'd get almost frantic，I also tried Android 8. It can run as well as Android 6. There is no problem in compiling and running.    The compilation of the lower version is OK, but the run fails, I think libmgr has a problem, but there's not enough evidence !!!

**Comment by enh-google** [comment]
where possible, the easiest and most compatible thing is to build all your code into one library. then there are no gotchas on any version of Android.
