### ISSUE TITLE
[question]  dlopen failed: cannot locate symbol "__executable_start". Need help!

### ISSUE THREAD

**Issue by LightSun** [android/ndk#1465]
I had use makefile to compiled pdfium from google's source. as a shared lib. but when I load it.  error happens.
```java
 Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__executable_start" referenced by "/data/app/com.github.barteksc.sample-2i9NLu3R8m2oImEBh8vodA==/lib/arm64/libpdfium.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.shockwave.pdfium.PdfiumCore.<clinit>(PdfiumCore.java:28)
        at com.github.barteksc.pdfviewer.PDFView.<init>(PDFView.java:266)
        	... 31 more
```
I don't know how to resolve, Could anyone help me ?

**Comment by DanAlbert** [comment]
> Could anyone help me ?

Unlikely without a repro case. This definitely looks like the library was not built correctly.

**Comment by LightSun** [comment]
I change the gcc-toolchain and sysroot. 
```java
--gcc-toolchain = $(ndk) /toolchains/llvm/prebuilt/windows-x86_64
--sysroot = $(ndk) /toolchains/llvm/prebuilt/windows-x86_64/sysroot
```
core makefile
```java
 OBJDIR              = ../../android-arm64/obj/Debug/pdfium
  TARGETDIR           = ../../android-arm64/bin
  TARGET              = $(TARGETDIR)/libpdfiumDebug.so
  DEFINES            += -DCCORE_ANDROID -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DHAVE_PTHREADS -DANDROID -DOPJ_STATIC -DOS_ANDROID -DWIN32_LEAN_AND_MEAN -DU_I18N_IMPLEMENTATION -DU_ICUDATAENTRY_IN_COMMON -DU_COMMON_IMPLEMENTATION -DU_STATIC_IMPLEMENTATION -DFT2_BUILD_LIBRARY -DARMV8_OS_ANDROID -DINFLATE_CHUNK_READ_64LE -D_DEBUG -DCCORE_THREAD_RR -DCCORE_CLOCK_TYPE_REALTIME
  INCLUDES           += -I"../../../src/main/PDFIUM" -I"../../../src/main/PDFIUM/public" -I"../../../src/main/PDFIUM/third_party/icu/source/i18n" -I"../../../src/main/PDFIUM/third_party/icu/source/common" -I"../../../src/main/PDFIUM/third_party/freetype/include/freetype/config" -I"../../../src/main/PDFIUM/third_party/freetype/src/include" -I"../../../src/main/PDFIUM/third_party/skia_shared" -I"../../../src/main/PDFIUM/third_party/cpufeatures" -I"$(ANDROID_SYSROOT)/usr/include" -I"$(ANDROID_NDK_ROOT)/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include" -I"$(ANDROID_SYSROOT)/usr/include/aarch64-linux-android"
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -fexceptions -frtti -pthread -fPIC -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -Wunused-value -Wundef -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) -target aarch64-none-linux-androideabi -march=armv8-a
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -fexceptions -frtti -pthread -fPIC -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -Wunused-value -Wundef -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) -target aarch64-none-linux-androideabi -march=armv8-a
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -fexceptions -frtti -pthread -fPIC -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -Wunused-value -Wundef -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) -target aarch64-none-linux-androideabi -march=armv8-a
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -fexceptions -frtti -pthread -fPIC -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -Wunused-value -Wundef -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) -target aarch64-none-linux-androideabi -march=armv8-a
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -O3 -fexceptions -frtti -pthread -fPIC -no-canonical-prefixes -Wa,--noexecstack -fstack-protector-strong -Wunused-value -Wundef -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) -target aarch64-none-linux-androideabi -march=armv8-a
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L"../../../prebuilds/android/arm64-v8a" -L"$(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android" -L"$(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android/21" -L"../../android-arm64/bin" -L"." -s -shared -pthread -no-canonical-prefixes -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Xlinker -zmuldefs -static-libstdc++ -funwind-tables -fstack-protector-strong -fno-addrsig -Wformat -Werror=format-security -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --gcc-toolchain=$(ANDROID_GCC_TOOLCHAIN) --sysroot=$(ANDROID_SYSROOT) $(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android/21/crtbegin_so.o $(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android/21/crtend_so.o -target aarch64-none-linux-androideabi -march=armv8-a
  LIBDEPS            += ../../android-arm64/bin/libfpdfdocDebug.a ../../android-arm64/bin/libfpdfapiDebug.a ../../android-arm64/bin/libfdrmDebug.a ../../android-arm64/bin/libfpdftextDebug.a ../../android-arm64/bin/libfxcodecDebug.a ../../android-arm64/bin/liblibjpegDebug.a ../../android-arm64/bin/libfx_lcms2Debug.a ../../android-arm64/bin/libfx_libopenjpegDebug.a ../../android-arm64/bin/libfx_zlibDebug.a ../../android-arm64/bin/libfxcrtDebug.a ../../android-arm64/bin/libfxgeDebug.a ../../android-arm64/bin/libfx_agg32Debug.a ../../android-arm64/bin/libfx_freetypeDebug.a ../../android-arm64/bin/libfx_icuDebug.a ../../android-arm64/bin/libfx_baseDebug.a
  LDDEPS             += ../../android-arm64/bin/libfpdfdocDebug.a ../../android-arm64/bin/libfpdfapiDebug.a ../../android-arm64/bin/libfdrmDebug.a ../../android-arm64/bin/libfpdftextDebug.a ../../android-arm64/bin/libfxcodecDebug.a ../../android-arm64/bin/liblibjpegDebug.a ../../android-arm64/bin/libfx_lcms2Debug.a ../../android-arm64/bin/libfx_libopenjpegDebug.a ../../android-arm64/bin/libfx_zlibDebug.a ../../android-arm64/bin/libfxcrtDebug.a ../../android-arm64/bin/libfxgeDebug.a ../../android-arm64/bin/libfx_agg32Debug.a ../../android-arm64/bin/libfx_freetypeDebug.a ../../android-arm64/bin/libfx_icuDebug.a ../../android-arm64/bin/libfx_baseDebug.a
  LDRESP              =
```
And the error log is 
```java
Linking pdfium
D:/study/android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android\libc.a(libc_init_common.o): In function `__libc_init_common()':
bionic/libc/bionic/libc_init_common.cpp:105: undefined reference to `pthread_atfork'
D:/study/android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android\libc.a(jemalloc.o): In function `je_malloc_disable_init':
external/jemalloc_new/src/android_je_iterate.c:91: undefined reference to `pthread_atfork'
D:/study/android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android\libc.a(jemalloc.o): In function `malloc_init_hard_recursible':
external/jemalloc_new/src/jemalloc.c:1367: undefined reference to `pthread_atfork'
D:/study/android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android\libc.a(dl_iterate_phdr_static.o): In function `dl_iterate_phdr':
bionic/libc/bionic/dl_iterate_phdr_static.cpp:45: undefined reference to `__executable_start'
bionic/libc/bionic/dl_iterate_phdr_static.cpp:45: undefined reference to `__executable_start'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pdfium.make:639: ../../android-arm64/bin/libpdfiumDebug.so] Error 1
make[1]: *** [Makefile:77: pdfium] Error 2
make[1]: Leaving directory 'E:/pros/lib_pdfium/.build/projects/gmake-android-arm64'
make: *** [makefile_win:93: android-arm64-debug] Error 2
```

**Comment by rprichard** [comment]
The build system is generating a shared library (libpdfiumDebug.so) but it's linking against libc.a, which is normally only linked into statically-linked executables. It should be linking against libc.so instead, and that's something the Clang driver handles automatically.

The order of these two arguments looks backwards:
```
-L"$(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android"
-L"$(ANDROID_SYSROOT)/usr/lib/aarch64-linux-android/21"
```
21 needs to come first because it has libc.so, while the other directory has libc.a.

Many of these options here shouldn't be necessary, though, because the Clang driver should add them automatically, as long as the `-target` option is passed. Instead of `-target aarch64-none-linux-androideabi`, pass `-target aarch64-linux-android21` (or some other API level).

e.g. These should be unnecessary to specify explicitly: --gcc-toolchain, --sysroot, crtbegin_so.o and crtend_so.o, and the two -L arguments shown above. The two -Wl,--exclude-libs arguments, on the other hand, aren't passed by the driver, and it's good to pass those yourself.

Maybe these links are helpful:
 - https://developer.android.com/ndk/guides/other_build_systems
 - https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Target-Selection (or [the version in the r21 branch](https://android.googlesource.com/platform/ndk/+/ndk-release-r21/docs/BuildSystemMaintainers.md#Target-Selection), which still shows ld.bfd/gold as the default linkers).

**Comment by LightSun** [comment]
@rprichard thanks. I'll try it.

**Comment by LightSun** [comment]
@rprichard thanks , I had resolved.
