### ISSUE TITLE
[question] when i build ndk, i encoutered this problems

### ISSUE THREAD

**Issue by dentiscalprum** [android/ndk#1522]
I used the method in this website, [](https://android.googlesource.com/toolchain/llvm_android/+/master/README.md)
thx!!!
```cpp
lchain/out/llvm-project/openmp/runtime/exports/lin_arm/lib
clang-11: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_atomic_end@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_atomic_end@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_atomic_start@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_atomic_start@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_barrier@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_barrier@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_barrier_cancel@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_barrier_cancel@GOMP_4.0 has undefined version GOMP_4.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_cancel@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_cancel@GOMP_4.0 has undefined version GOMP_4.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_cancellation_point@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_cancellation_point@GOMP_4.0 has undefined version GOMP_4.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_end@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_end@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_name_end@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_name_end@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_name_start@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_name_start@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_start@@VERSION has undefined version VERSION
ld.lld: error: runtime/src/CMakeFiles/omp.dir/kmp_gsupport.cpp.o: symbol GOMP_critical_start@GOMP_1.0 has undefined version GOMP_1.0
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 710, in <module>
    main()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 681, in main
    build_runtimes(build_lldb_server=build_lldb)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 118, in build_runtimes
    builders.LibOMPBuilder().build()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/builder_registry.py", line 67, in wrapper
    function(builder, *args, **kwargs)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 89, in build
    self._build_config()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 350, in _build_config
    utils.check_call(ninja_cmd, cwd=self.output_dir, env=env)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 52, in check_call
    return subprocess_run(cmd, *args, **kwargs, check=True)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 42, in subprocess_run
    return subprocess.run(cmd, *args, **kwargs, text=True)
  File "/root/opt/llvm-toolchain/prebuilts/python/linux-x86/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/opt/llvm-toolchain/prebuilts/build-tools/linux-x86/bin/ninja']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "toolchain/llvm_android/build.py", line 21, in <module>
    py3_utils.run_with_py3('do_build.py')
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/py3_utils.py", line 36, in run_with_py3
    [python_bin, os.path.join(THIS_DIR, script_name)] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/opt/llvm-toolchain/prebuilts/python/linux-x86/bin/python3', '/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py', '--no-build', 'windows']' returned non-zero exit status 1

**Comment by pirama-arumuga-nainar** [comment]
Can you post the clang version (`clang -v`) you're trying to re-build?

**Comment by dentiscalprum** [comment]
```cpp
Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/.
Found candidate GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/i686-linux-android/4.9.x
Found candidate GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/x86_64-linux-android/4.9.x
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/x86_64-linux-android/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
thx

**Comment by pirama-arumuga-nainar** [comment]
Sorry for the delay in responding here.  I can build this prebuilt to completion.  Can you clean the out directory and retry?  If it repros, can you share a repro?
- get the failing command (`/root/opt/llvm-toolchain/prebuilts/build-tools/linux-x86/bin/ninja -v`) in the failing build directory.
- re-run it with `-Wl,--reproduce=failure.tar` and share `failure.tar`.
