### ISSUE TITLE
[question]when i build ndk,  I encountered some errors

### ISSUE THREAD

**Issue by dentiscalprum** [android/ndk#1524]
I compile according to the way of this website and encountered this error, can you please provide a way to solve this problem
[](https://android.googlesource.com/toolchain/llvm_android/#instructions-to-rebuild-a-particular-toolchain-release)
```cpp
  CCLD     libedit.la
make[3]: *** [Makefile:454: libedit.la] Error 1
make[3]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux/src'
make[2]: *** [Makefile:384: all] Error 2
make[2]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux/src'
make[1]: *** [Makefile:455: all-recursive] Error 1
make[1]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux'
make: *** [Makefile:364: all] Error 2
Traceback (most recent call last):
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 710, in <module>
    main()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 663, in main
    libedit_builder.build()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/builder_registry.py", line 67, in wrapper
    function(builder, *args, **kwargs)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 89, in build
    self._build_config()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 217, in _build_config
    utils.check_call(make_cmd, cwd=self.output_dir)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 52, in check_call
    return subprocess_run(cmd, *args, **kwargs, check=True)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 42, in subprocess_run
    return subprocess.run(cmd, *args, **kwargs, text=True)
  File "/root/opt/llvm-toolchain/prebuilts/python/linux-x86/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "toolchain/llvm_android/build.py", line 21, in <module>
    py3_utils.run_with_py3('do_build.py')
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/py3_utils.py", line 36, in run_with_py3
    [python_bin, os.path.join(THIS_DIR, script_name)] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/opt/llvm-toolchain/prebuilts/python/linux-x86/bin/python3', '/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py', '--no-build', 'windows']' returned non-zero exit status 1
```
$ uname -a
Linux boulevard-virtual-machine 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
thx!!!

**Comment by enh-google** [comment]
i think you've missed out the actual error that caused make to fail there... you probably need to scroll back to see it...

**Comment by dentiscalprum** [comment]
ndk version
```cpp 
Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/.
Found candidate GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/i686-linux-android/4.9.x
Found candidate GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/x86_64-linux-android/4.9.x
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /root/opt/android-ndk-r22b/toolchains/llvm/prebuilt/linux-x86_64/bin/./../lib/gcc/x86_64-linux-android/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

```cpp
make[3]: Entering directory '/root/opt/llvm-toolchain/out/lib/libedit-linux/src'
  CC       common.lo
  CC       chared.lo
  CC       emacs.lo
  CC       keymacro.lo
  CC       map.lo
  CC       read.lo
  CC       search.lo
  CC       sig.lo
  CC       terminal.lo
/root/opt/llvm-toolchain/external/libedit/src/terminal.c:591:28: warning: passing 'wint_t *' (aka 'unsigned int *') to parameter of type 'const wchar_t *' (aka 'const int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                                terminal_overwrite(el, &el->el_display[
                                                       ^~~~~~~~~~~~~~~~
/root/opt/llvm-toolchain/external/libedit/src/terminal.h:95:68: note: passing argument to parameter here
libedit_private void    terminal_overwrite(EditLine *, const wchar_t *, size_t);
                                                                      ^
  CC       tty.lo
1 warning generated.
  CC       vi.lo
  CC       readline.lo
  CCLD     libedit.la
make[3]: *** [Makefile:454: libedit.la] Error 1
make[3]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux/src'
make[2]: *** [Makefile:384: all] Error 2
make[2]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux/src'
make[1]: *** [Makefile:455: all-recursive] Error 1
make[1]: Leaving directory '/root/opt/llvm-toolchain/out/lib/libedit-linux'
make: *** [Makefile:364: all] Error 2
Traceback (most recent call last):
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 710, in <module>
    main()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py", line 663, in main
    libedit_builder.build()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/builder_registry.py", line 67, in wrapper
    function(builder, *args, **kwargs)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 89, in build
    self._build_config()
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/base_builders.py", line 217, in _build_config
    utils.check_call(make_cmd, cwd=self.output_dir)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 52, in check_call
    return subprocess_run(cmd, *args, **kwargs, check=True)
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/utils.py", line 42, in subprocess_run
    return subprocess.run(cmd, *args, **kwargs, text=True)
  File "/root/opt/llvm-toolchain/prebuilts/python/linux-x86/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', '-j2']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "toolchain/llvm_android/build.py", line 21, in <module>
    py3_utils.run_with_py3('do_build.py')
  File "/root/opt/llvm-toolchain/toolchain/llvm_android/py3_utils.py", line 36, in run_with_py3
    [python_bin, os.path.join(THIS_DIR, script_name)] + sys.argv[1:])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/opt/llvm-toolchain/prebuilts/python/linux-x86/bin/python3', '/root/opt/llvm-toolchain/toolchain/llvm_android/do_build.py', '--no-build', 'windows']' returned non-zero exit status 1
```
 please take a look， thx

**Comment by DanAlbert** [comment]
There's still no actual error message here for us to investigate. All you've shown is the message that says "something went wrong in the build" and the _warnings_ in the build, which don't matter. We need the _error_ from the build to be able to help.
